charms:
  charm_one:
    material: IRON_INGOT
    name: Test
    lore: Test
    effects:
      effect_one:
        type: STRENGTH
        amplifier: 6
      effect_two:
        type: SPEED
        amplifier: 8
  charm_two:
    material: APPLE
    name: Test
    lore: Test
    effects:
      effect_one:
        type:
        amplifier:
  charm_three:
    material: SEA_LANTERN
    name: Test
    lore: Test
    effects:
      effect_one:
        type:
        amplifier:
  