charms:
  charm_one:
    material: IRON_INGOT
    name: Steel Power
    lore: Not sure what to say about this...
    effects:
      effect_one:
        type: STRENGTH
        amplifier: 6
      effect_two:
        type: SPEED
        amplifier: 8
  charm_two:
    material: APPLE
    name: Death's Grace
    lore: Reach high places and shorten your lifespan!
    effects:
      effect_one:
        type: HUNGER
        amplifier: 11
      effect_two:
        type: BLINDNESS
        amplifier: 3
      effect_one:
        type: JUMP_BOOST
        amplifier: 15
  charm_three:
    material: SEA_LANTERN
    name: Sea Power
    lore: Stay hydrated!
    effects:
      effect_one:
        type: ABSORPTION
        amplifier: 25
  