charms:
  charm_one:
    material: IRON_INGOT
    name: Steel Power
    lore: ยง4Not sure what to say about this...
    glow: true
    effects:
      strength:
        type: STRENGTH
        amplifier: 6
      speed:
        type: SPEED
        amplifier: 8
  charm_two:
    material: APPLE
    name: ยง7Death's Grace
    lore: Reach high places and shorten your lifespan!
    glow: true
    effects:
      hunger:
        type: HUNGER
        amplifier: 6
      blindness:
        type: BLINDNESS
        amplifier: 3
      jump_boost:
        type: JUMP_BOOST
        amplifier: 15
  charm_three:
    material: SEA_LANTERN
    name: Sea Power
    lore: Stay hydrated!
    glow: false
    effects:
      absorption:
        type: ABSORPTION
        amplifier: 25
  